apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: default
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.27.4-k3s1

volumes:
  - volume: /home/ubuntu/k3d/data:/mnt/data
    nodeFilters:
      - all

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3d:
    wait: true
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable-cloud-controller
        nodeFilters:
          - server:*
      - arg: --default-local-storage-path=/mnt/data
        nodeFilters:
          - server:*