apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: switchblade
  name: switchblade-metrics-service
  namespace: boundless-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: switchblade

