---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: switchblade
rules:
- apiGroups:
  - web.boundless.software
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - aws.boundless.software
  resources:
  - rds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.boundless.software
  resources:
  - rds/finalizers
  verbs:
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - rds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - ec2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.boundless.software
  resources:
  - ec2s/finalizers
  verbs:
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - ec2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - eks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.boundless.software
  resources:
  - eks/finalizers
  verbs:
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - eks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - iams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.boundless.software
  resources:
  - iams/finalizers
  verbs:
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - iams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.boundless.software
  resources:
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - aws.boundless.software
  resources:
  - vpcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - resourcequotas
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.boundless.software
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.boundless.software
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - core.boundless.software
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.boundless.software
  resources:
  - helms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.boundless.software
  resources:
  - helms/finalizers
  verbs:
  - update
- apiGroups:
  - core.boundless.software
  resources:
  - helms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.boundless.software
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.boundless.software
  resources:
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - core.boundless.software
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - '*'
