# # /home/akhil/workspace/projects/boundless/switchblade/bin/controller-gen rbac:roleName=switchblade crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
# # test -s /home/akhil/workspace/projects/boundless/switchblade/bin/kustomize || { curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 4.5.7 /home/akhil/workspace/projects/boundless/switchblade/bin; }
# # {Version:kustomize/v4.5.7 GitCommit:56d82a8378dfc8dc3b3b1085e5a6e67b82966bd7 BuildDate:2022-08-02T16:35:54Z GoOs:linux GoArch:amd64}
# # kustomize installed to /home/akhil/workspace/projects/boundless/switchblade/bin/kustomize
# # cd config/manager && /home/akhil/workspace/projects/boundless/switchblade/bin/kustomize edit set image controller=switchblade:latest
# # /home/akhil/workspace/projects/boundless/switchblade/bin/kustomize build config/default
apiVersion: v1
kind: Namespace
metadata:
  name: boundless-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: switchblade
    meta.helm.sh/release-namespace: boundless-system