apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsCredentials.name }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.secretAccessKey }}
