apiVersion: v1
entries:
  switchblade:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-10-28T12:15:55.097937948-04:00"
    description: A Helm chart for Kubernetes
    digest: 30e48d7670c3c7c6cbc2be26008af2112794b006a42f2194699a679e85915e24
    icon: https://i0.wp.com/boundless.software/wp-content/uploads/2023/06/CLOUD-LOGO-white.png?resize=146%2C88&ssl=1
    name: switchblade
    type: application
    urls:
    - switchblade-0.0.19.tgz
    version: 0.0.19
generated: "2024-10-28T12:15:55.076325912-04:00"
