apiVersion: v1
entries:
  switchblade:
  - apiVersion: v2
    appVersion: release-v0.0.19-lcm
    created: "2025-04-03T18:10:03.246479782-04:00"
    description: A Helm chart for Kubernetes
    digest: 7c667008c1e7852830fd5052d779ebe028715e2d9520cb2371fc393cd838165b
    icon: https://i0.wp.com/boundless.software/wp-content/uploads/2023/06/CLOUD-LOGO-white.png?resize=146%2C88&ssl=1
    name: switchblade
    type: application
    urls:
    - switchblade-0.0.19.tgz
    version: 0.0.19
generated: "2025-04-03T18:10:03.240791266-04:00"
